services:
  webapi:
    container_name: marina-tour-web
    image: 0605abmu/marina-tour-web
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://*:8080
    healthcheck:
      test: curl -f http://localhost:8080/healthy
      interval: 10s
    ports:
      - "8081:8080"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      
