name: Backend Production Deploy

on: 
  push:
    branches: master

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v4.1.7
      - name: Docker login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}
      - name: Build
        run: docker compose -f docker-compose.yml build
      - name: Push
        run: docker compose push
        
  Deploy:
    runs-on: ubuntu-latest
    needs: [Publish]
    steps:
      - name: Connect to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          password: ${{secrets.SERVER_PASSWORD}}
          script: cd /home/abmu/marina-tour
      - name: Pull
        run: docker compose pull
      - name: Down
        run: docker compose down
      - name: Up
        run: docker compose up -d
  
